# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

xcodeproj ‘./MTMediaPlayer.xcodeproj'

target ‘MTMediaPlayer’ do
    pod 'TransitionKit'
	pod 'AFNetworking',       '~> 2.5.1'
    pod 'FrameAccessor',      '~> 1.3.2'
    pod 'MBProgressHUD',      '~> 0.9'
    pod 'OpenUDID',           '~> 1.0.0'
    pod 'Reachability',       '~> 3.2'
    pod 'RegexKitLite',       '~> 4.0'
    pod 'SDWebImage',         '~> 3.7.2'
    pod 'SevenSwitch',        '~> 1.3.0'
    pod 'Toast',              '~> 2.2'
    pod 'UIAlertView-Blocks', '~> 1.0'
    pod 'XMLDictionary',      '~> 1.3'
	pod 'PureLayout',           '~> 2.0.6'
    pod 'UIAlertView-Blocks', '~> 1.0'
    pod 'DZNEmptyDataSet',    '~> 1.5.2'
    pod 'Mantle',             '~> 1.3'
    pod 'HexColors',		  '~> 2.2.1'
    pod 'CocoaHTTPServer',    '~> 2.3'

    pod 'MTVideoCacheKit', :git => 'git@techgit.meitu.com:iosmodules/MTVideoCache.git', :branch => 'cachedemo_urlsession'
    
    
#Warning Customized pods, need to manually update
#pod install --verbose --no-repo-update
#pod update --verbose --no-repo-update

end


