# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

#inhibit_all_warnings!

#xcodeproj ‘./CJMediaPlayer.xcodeproj'

target ‘CJMediaPlayerDemo’ do
    pod 'CQDemoKit',          '~> 0.7.5',      :subspecs => ['BaseVC']
    
    pod 'CJPlayer',           :path => '../'
    pod 'CJMediaPlayer',      :path => '../'
    pod 'CJMediaCacheKit',    :path => '../'
    
    pod 'MBProgressHUD',      '~> 0.9'
    
#    pod 'TBPlayer',    '~> 1.0'

end


