# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

#inhibit_all_warnings!

#xcodeproj ‘./CJMediaPlayer.xcodeproj'

target ‘CJMediaPlayerDemo’ do
    pod 'TransitionKit'
    pod 'Toast',              '~> 2.2'
    
	pod 'AFNetworking',       '~> 2.5.1'
    pod 'Reachability',       '~> 3.2'
    
    pod 'CocoaHTTPServer',    '~> 2.3'
    
    pod 'SDWebImage',         '~> 3.7.2'
    pod 'MBProgressHUD',      '~> 0.9'
    pod 'PureLayout',           '~> 2.0.6'
    
    pod 'CJBaseUIKit/CJSlider/CJPlayerSlider', '~> 0.0.7'
    pod 'CJFoundation/NSString', '~> 0.0.1' #实际上顶多只用到了NSString里面的CJEncoding
    
#    pod 'TBPlayer',    '~> 1.0'

end


